inputs:
  elasticsearch-versin:
    description: 'Elasticsearch version'
  lucene-version:
    description: 'Lucene version'
    default: ''
  java-version:
    description: 'Java version'
    default: ''
outputs:
  commit-message:
    description: 'Commit message'
    value: ${{ steps.commit_message.outputs.message }}
runs:
  using: 'composite'
  steps:
    - name: Create Commit Message
      id: commit_message
      shell: bash
      run: |
        echo "::set-output name=message::hello"
