language: java
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  skip_cleanup: true
  file: target/releases/analysis-homoglyph-0.2.0.zip
  on:
    tags: true
script:
- mvn package
